Models/Weather.cs
namespace Models
{
    public class Weather
    {
        public int id { get; set; }
        public string main { get; set; }
        public string description { get; set; }
        public string icon { get; set; }
    }
}

ViewModels/WeatherViewModel.cs
using Models;

namespace WeatherApp.ViewModels
{
    public class WeatherViewModel
    {
        public IEnumerable<IGrouping<DateTime, List>>? GroupedWeather { get; set; }
        public string? Date {  get; set; }
        public string? City { get; set; }
    }
}

Components/DayIconViewComponent.cs
using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using WeatherApp.ViewModels;

namespace WeatherApp.Components
{
    public class DayIconViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(IGrouping<DateTime, Models.List> item)
        {
            if (item == null || string.IsNullOrEmpty(TempData["City"]?.ToString()))
            {
                return View("Error", "No data available for the selected day.");
            }

            string iconName = item.FirstOrDefault(i => i.dt_txt.EndsWith("12:00:00"))?.weather.First().icon ?? item.First().weather.First().icon;

            var viewModel = new DayViewModel
            {
                Date = item.Key,
                IconUrl = $"/images/{iconName}.png",
                IsSelected = ViewData.ContainsKey("selected") && (bool)ViewData["selected"] == true,
                City = TempData["City"]?.ToString()
            };

            return View(viewModel);
        }
    }
}

Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using Models;
using Services;
using System.Globalization;
using Microsoft.VisualBasic;
using ServiceContracts;
using WeatherApp.ViewModels;
using Microsoft.Extensions.Caching.Memory;

namespace WeatherApp.Controllers 
{
    public class WeatherController : Controller
    {
        private readonly IWeatherService _weatherService;
        private readonly IMemoryCache _memoryCache;
        private readonly TimeSpan _cacheDuration = TimeSpan.FromMinutes(30);
        public WeatherController(IWeatherService weatherService, IMemoryCache memoryCache)
        {
            _weatherService = weatherService;
            _memoryCache = memoryCache;
        }
        [Route("/")]
        public IActionResult Index(string city = "Kyiv")
        {
            ViewData["City"] = city;
            return RedirectToAction("Search", new {city = "Kyiv"});
        }

        [Route("Search")]
        [Route("{city}")]
        public async Task<IActionResult> Search(string city = "Kyiv")
        {
            if (!string.IsNullOrEmpty(city))
            {
                city = city.Trim();

                if (!_memoryCache.TryGetValue(city, out WeatherResponse? weather))
                {
                    try
                    {
                        weather = await _weatherService.GetWeatherResponseAsync(city);

                        _memoryCache.Set(city, weather, _cacheDuration);
                    }
                    catch (Exception)
                    {
                        if (city == "Error")
                        {
                            return View("Error");
                        }
                        return View("NotFound");
                    }
                }
                
                var FiveDaysWeather = weather?.list
                    .GroupBy(item => DateTime.ParseExact(
                    item.dt_txt, "yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture).Date);

                var weatherViewModel = new WeatherViewModel()
                {
                    City = city,
                    GroupedWeather = FiveDaysWeather
                };

                return View("Index", weatherViewModel);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [Route("{city}/{date:length(10)}")]
        [HttpPost("{city}/{date:length(10)}")]
        public async Task<IActionResult> ShowDetails(string city, string date)
        {
            if (string.IsNullOrEmpty(city) ||
                !DateTime.TryParseExact(date, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None,
                out DateTime parsedDate))
            {
                return BadRequest("Invalid city or date format.");
            }

            if (!_memoryCache.TryGetValue(city, out WeatherResponse? weather))
            {
                weather = await _weatherService.GetWeatherResponseAsync(city);
                _memoryCache.Set(city, weather, _cacheDuration);
            }

            var FiveDaysWeather = weather?.list
                .GroupBy(item => DateTime.ParseExact(item.dt_txt, "yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture).Date);

            var weatherViewModel = new WeatherViewModel()
            {
                City = city,
                Date = date,
                GroupedWeather = FiveDaysWeather
            };

            return View("Index", weatherViewModel);
        }
    }
}

Views/Weather/Index.cshtml
@model WeatherViewModel

<div class="container p-2">
    <div class="d-flex justify-content-center">
        <div class="card-group" style="white-space: nowrap;">
            @{
                foreach (var weatherItem in Model.GroupedWeather)
                {
                    <form asp-action="ShowDetails" asp-controller="Weather" method="post">
                        <input type="hidden" name="date" value="@weatherItem.Key.ToString("yyyy-MM-dd")" />
                        <input type="hidden" name="city" value="@Model.City"/>

                        @{
                            if (!string.IsNullOrEmpty(Model.Date))
                            {
                                int parsedDay = DateTime.ParseExact(Model.Date.ToString(), "yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture).DayOfYear;
                                int actualDay = weatherItem.Key.DayOfYear;

                                bool selected = (parsedDay == actualDay);
                                ViewData["selected"] = selected;
                            }

                            TempData["City"] = Model.City;
                        }
                       <vc:day-icon item="weatherItem"/>

                    </form>
                }
            }
        </div>
    </div>

    <div style="margin-left: 10%; margin-top: 15px;">
        @if (!string.IsNullOrEmpty(Model.Date))
        {
            TempData["selectedDay"] = Model.Date;

            var selectedModel = Model.GroupedWeather
                .SelectMany(group => group)
                .GroupBy(item => DateTime.ParseExact(item.dt_txt, "yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture).Date)
                .FirstOrDefault(group => group.Key == DateTime.ParseExact(Model.Date as string, "yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture).Date);

            @await Component.InvokeAsync("DayDetails", selectedModel)
        }
        else
        {
            TempData["City"] = Model.City;

            var selectedModel = Model.GroupedWeather.First();
            @await Component.InvokeAsync("DayDetails", selectedModel)   
        }
    </div>
</div>