ViewModels/DayDetailsViewModel.cs
namespace WeatherApp.ViewModels
{
    public class DayDetailsViewModel
    {
        public string? City { get; set; }
        public IGrouping<DateTime, Models.List>? DayInfo {get; set;}
    }
}

Components/DayIconViewComponent.cs
using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using WeatherApp.ViewModels;

namespace WeatherApp.Components
{
    public class DayIconViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(IGrouping<DateTime, Models.List> item)
        {
            if (item == null || string.IsNullOrEmpty(TempData["City"]?.ToString()))
            {
                return View("Error", "No data available for the selected day.");
            }

            string iconName = item.FirstOrDefault(i => i.dt_txt.EndsWith("12:00:00"))?.weather.First().icon ?? item.First().weather.First().icon;

            var viewModel = new DayViewModel
            {
                Date = item.Key,
                IconUrl = $"/images/{iconName}.png",
                IsSelected = ViewData.ContainsKey("selected") && (bool)ViewData["selected"] == true,
                City = TempData["City"]?.ToString()
            };

            return View(viewModel);
        }
    }
}

Components/UnitsChangeViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WeatherApp.ViewModels;

namespace WeatherApp.Components
{
    public class UnitsChangeViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using Models;
using Services;
using System.Globalization;
using Microsoft.VisualBasic;
using ServiceContracts;
using WeatherApp.ViewModels;
using Microsoft.Extensions.Caching.Memory;

namespace WeatherApp.Controllers 
{
    public class WeatherController : Controller
    {
        private readonly IWeatherService _weatherService;
        private readonly IMemoryCache _memoryCache;
        private readonly TimeSpan _cacheDuration = TimeSpan.FromMinutes(30);
        public WeatherController(IWeatherService weatherService, IMemoryCache memoryCache)
        {
            _weatherService = weatherService;
            _memoryCache = memoryCache;
        }
        [Route("/")]
        public IActionResult Index(string city = "Kyiv")
        {
            ViewData["City"] = city;
            return RedirectToAction("Search", new {city = "Kyiv"});
        }

        [Route("Search")]
        [Route("{city}")]
        public async Task<IActionResult> Search(string city = "Kyiv")
        {
            if (!string.IsNullOrEmpty(city))
            {
                city = city.Trim();

                if (!_memoryCache.TryGetValue(city, out WeatherResponse? weather))
                {
                    try
                    {
                        weather = await _weatherService.GetWeatherResponseAsync(city);

                        _memoryCache.Set(city, weather, _cacheDuration);
                    }
                    catch (Exception)
                    {
                        if (city == "Error")
                        {
                            return View("Error");
                        }
                        return View("NotFound");
                    }
                }
                
                var FiveDaysWeather = weather?.list
                    .GroupBy(item => DateTime.ParseExact(
                    item.dt_txt, "yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture).Date);

                var weatherViewModel = new WeatherViewModel()
                {
                    City = city,
                    GroupedWeather = FiveDaysWeather
                };

                return View("Index", weatherViewModel);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [Route("{city}/{date:length(10)}")]
        [HttpPost("{city}/{date:length(10)}")]
        public async Task<IActionResult> ShowDetails(string city, string date)
        {
            if (string.IsNullOrEmpty(city) ||
                !DateTime.TryParseExact(date, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None,
                out DateTime parsedDate))
            {
                return BadRequest("Invalid city or date format.");
            }

            if (!_memoryCache.TryGetValue(city, out WeatherResponse? weather))
            {
                weather = await _weatherService.GetWeatherResponseAsync(city);
                _memoryCache.Set(city, weather, _cacheDuration);
            }

            var FiveDaysWeather = weather?.list
                .GroupBy(item => DateTime.ParseExact(item.dt_txt, "yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture).Date);

            var weatherViewModel = new WeatherViewModel()
            {
                City = city,
                Date = date,
                GroupedWeather = FiveDaysWeather
            };

            return View("Index", weatherViewModel);
        }
    }
}

Views/Shared/Components/DayDetails/Default.cshtml
@using System.Globalization
@using WeatherApp.Extentions
@model DayDetailsViewModel

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

<div class="row">
    <div class="col">
        <h2>Weather in @Model.City?.FirstToUpper() on <i>@Model.DayInfo?.Key.ToString("MMMM dd, yyyy")</i></h2>
    </div>
    <div class="col-auto">
        <form asp-action="ChangeUnits" asp-controller="Weather" method="post">
            <vc:units-change/>
        </form>
    </div>
</div>

<table class="table table-bordered table-responsive text-center">
    <thead>
        <tr>
            <th class="align-middle">Time</th>
            @foreach (var weather in Model.DayInfo)
            {
                <th style="padding-top: 15px">
                    @DateTime.ParseExact(weather.dt_txt, "yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture).ToString("HH:mm")
                    <br />
                    <img src="/images/@(weather.weather.First().icon).png" style="max-width: 80px; height: auto;" />
                </th>
            }
        </tr>
    </thead>
    <tbody class="align-middle">
        <tr>
            <td id="temperature"><b>Temperature (&#8451;)</b></td>
            @foreach (var weather in Model.DayInfo)
            {
                <td id="temperaturevalue">@Math.Round(weather.main.temp)&#176</td>
            }
        </tr>
        <tr>
            <td id="feelslike"><b>Feels Like (&#8451;)</b></td>
            @foreach (var weather in Model.DayInfo)
            {
                <td id="feelslikevalue">@Math.Round(weather.main.feels_like)&#176</td>
            }
        </tr>
        <tr>
            <td><b>Pressure (mm)</b></td>
            @foreach (var weather in Model.DayInfo)
            {
                <td>@weather.main.pressure</td>
            }
        </tr>
        <tr>
            <td><b>Humidity (%)</b></td>
            @foreach (var weather in Model.DayInfo)
            {
                <td>@weather.main.humidity</td>
            }
        </tr>
        <tr>
        <td id="wind"><b>Wind (m/s)</b></td>
            @foreach (var weather in Model.DayInfo)
            {
                <td title = "@GetWindDirection(@weather.wind.deg)">
                    <i class="fa-solid fa-arrow-up" style="transform: rotate(@GetArrowRotation(weather.wind.deg)); font-size: 14px; margin-right: 5px;"></i>
                    <span id="windspeed">@weather.wind.speed</span>
                </td>            
            }
        </tr>
        <tr>
            <td><b/>Probability of precipitation (%)<b/></td>
            @foreach (var weather in Model.DayInfo)
            {
                <td>@Convert.ToInt32(weather.pop * 100)</td>
            }
        </tr>
    </tbody>
</table>

@{
    static string GetWindDirection(double deg)
    {
        switch (true)
        {
            case var expression when deg > 337.5:
                return "Northerly";
            case var expression when deg > 292.5:
                return "North Westerly";
            case var expression when deg > 247.5:
                return "Westerly";
            case var expression when deg > 202.5:
                return "South Westerly";
            case var expression when deg > 157.5:
                return "Southerly";
            case var expression when deg > 122.5:
                return "South Easterly";
            case var expression when deg > 67.5:
                return "Easterly";
            case var expression when deg > 22.5:
                return "North Easterly";
            default:
                return "Northerly";
        }
    }

    static string GetArrowRotation(double deg)
    {
        double rotation = (deg + 180) % 360;
        return $"{rotation}deg";
    }
}